name       : libtheora
version    : 1.1.1
release    : 6
source     :
    - https://github.com/xiph/theora/archive/v1.1.1.tar.gz : 1d5c3b25bbced448f3e741c42df6796e3d5e57136a74bcd68262318290ec2982
homepage   : http://www.theora.org
license    : BSD
emul32     : yes
component  : multimedia.codecs
summary    : Open source video format
description: |
    Theora is a free and open video compression format.
patterns   :
    - docs : [/usr/share/doc/]
builddeps  :
    - pkgconfig(ogg)
    - pkgconfig32(ogg)
    - pkgconfig(vorbis)
    - pkgconfig32(vorbis)
    - glibc-32bit-devel
    - libgcc-32bit
setup      : |
    %autogen --disable-static \
        --disable-examples \
        --disable-sdltest
build      : |
    %make
install    : |
    %make_install
